# The URL the site will be built for
base_url = "https://rust-lang.tw"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hallo"

title = "Rust Taiwan Community"

[extra]
# Put all your custom variables here
author = { name = "Rust Taiwan" }
iam = "Welcome to"
links = [
    { title = "Telegram 群組", url = "https://t.me/rust_tw", icon = "telegram" },
    { title = "Facebook 群組", url = "https://www.facebook.com/groups/857846870916793/", icon = "facebook" },
    { title = "GitHub", url = "https://github.com/rust-tw/", icon = "github" },
    { title = "E-mail", url = "mailto:contact@rust-lang.tw", iconset = "fas", icon = "envelope" },
]